### ISSUE TITLE
Feature Request: Support for Pub/Sub Message attributes

### ISSUE THREAD

**Issue by henryharbeck** [stape-io/pub-sub-publish-tag#1]
Thank you for the great tag template.

I am wondering whether it would be possible to support Pub/Sub Message `attributes`, as detailed on [this page](https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage). I would like to filter messages on the subscription of the topic, and require attributes to do so.

This could function similarly to the "Custom Data" field, where attributes can be added as key-value pairs.

I would be open to submitting a PR if this feature request is accepted.

Cheers

**Comment by Bukashk0zzz** [comment]
Hi,

Good idea. 
PR is welcome. 

Thanks.
